export const input = {
	$schema: 'https://json-schema.org/draft-07/schema',
	type: 'object',
	oneOf: [
		{ $ref: '../definitions/CatalogItemReaderStep.json' },
		{ $ref: '../definitions/ConditionStep.json' },
		{ $ref: '../definitions/DbWriterStep.json' },
		{ $ref: '../definitions/DeleteAttributeStep.json' },
		{ $ref: '../definitions/EmbeddedPlanStep.json' },
		{ $ref: '../definitions/FilterStep.json' },
		{ $ref: '../definitions/GroupAggregatorStep.json' },
		{ $ref: '../definitions/InputStep.json' },
		{ $ref: '../definitions/JoinStep.json' },
		{ $ref: '../definitions/OneDataWriterStep.json' },
		{ $ref: '../definitions/OutputStep.json' },
		{ $ref: '../definitions/RulePlanStep.json' },
		{ $ref: '../definitions/SplitStreamStep.json' },
		{ $ref: '../definitions/TransformDataStep.json' },
		{ $ref: '../definitions/TransformationCatalogItemOutputStep.json' },
		{ $ref: '../definitions/UnionStreamStep.json' },
	],
};
