export const formatToZodMethod: Record<string, string> = {
	email: '.email()',
	uuid: '.uuid()',
	url: '.url()',
	uri: '.url()',
	emoji: '.emoji()',
	base64: '.base64()',
	base64url: '.base64url()',
	nanoid: '.nanoid()',
	cuid: '.cuid()',
	cuid2: '.cuid2()',
	ulid: '.ulid()',
	ipv4: '.ipv4()',
	ipv6: '.ipv6()',
	cidrv4: '.cidrv4()',
	cidrv6: '.cidrv6()',
	date: '.iso.date()',
	time: '.iso.time()',
	'date-time': '.iso.datetime()',
	duration: '.iso.duration()',
};
